export default {
  TOGGLE_POPUP: 'TOGGLE_POPUP',
  SET_MARKER: 'SET_MARKER',
  SAVE_LOCATIONS: 'SAVE_LOCATIONS',
  SAVE_USER_LOCATIONS: 'SAVE_USER_LOCATIONS',
  SAVE_GROUPS: 'SAVE_GROUPS',
  SAVE_CATEGORIES: 'SAVE_CATEGORIES',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  SET_LOCATION: 'SET_LOCATION',
  TOGGLE_SHOW_FOUND: 'TOGGLE_SHOW_FOUND',
  TOGGLE_SHOW_HIDE_CATEGORY: 'TOGGLE_SHOW_HIDE_CATEGORY',
  SAVE_TOKEN: 'SAVE_TOKEN',
}
